#!/usr/bin/env python3
"""Builds rugby.js: the world rugby union edition.  Run: python3 connections/tools/build_rugby.py [-v]"""
from edition import C, run

# id: (tile, clue, year/era, note for the results screen)
ITEMS = {
  # national sides
  'england':     ("England", "Six Nations", "", "World champions 2003"),
  'france':      ("France", "Six Nations", "", "Hosted the 2007 and 2023 World Cups"),
  'ireland':     ("Ireland", "Six Nations", "", ""),
  'scotland':    ("Scotland", "Six Nations", "", ""),
  'wales':       ("Wales", "Six Nations", "", "Hosted the 1999 World Cup"),
  'italy':       ("Italy", "Six Nations", "", "Joined in 2000"),
  'allblacks':   ("All Blacks", "New Zealand", "", "World champions 1987, 2011, 2015"),
  'springboks':  ("Springboks", "South Africa", "", "World champions 1995, 2007, 2019, 2023"),
  'wallabies':   ("Wallabies", "Australia", "", "World champions 1991, 1999"),
  'pumas':       ("Pumas", "Argentina", "", "Joined the Rugby Championship in 2012"),
  'braveblossoms':("Brave Blossoms", "Japan", "", "Named for the cherry blossom on the jersey"),
  'fiji':        ("Flying Fijians", "Fiji", "", ""),
  'samoa':       ("Samoa", "Pacific nation", "", "Their war dance is the Siva Tau"),
  'tonga':       ("Tonga", "Pacific nation", "", "Their war dance is the Sipi Tau"),
  'georgia':     ("Georgia", "Europe's best outside the Six Nations", "", "Nicknamed the Lelos"),
  'portugal':    ("Portugal", "European nation", "", "Os Lobos — the wolves"),
  'romania':     ("Romania", "European nation", "", "The Oaks"),
  'spain':       ("Spain", "European nation", "", ""),
  'blackferns':  ("Black Ferns", "New Zealand women", "", "Six-time women's world champions"),
  'redroses':    ("Red Roses", "England women", "", "Women's world champions 1994, 2014, 2025"),
  'barbarians':  ("Barbarians", "Invitation side", "1890", "The Baa-Baas"),
  # Super Rugby & clubs
  'crusaders':   ("Crusaders", "Christchurch", "", "Super Rugby's most successful side"),
  'blues':       ("Blues", "Auckland", "", ""),
  'chiefs':      ("Chiefs", "Hamilton", "", ""),
  'hurricanes':  ("Hurricanes", "Wellington", "", ""),
  'highlanders': ("Highlanders", "Dunedin", "", ""),
  'brumbies':    ("Brumbies", "Canberra", "", "Named after wild horses"),
  'waratahs':    ("Waratahs", "Sydney", "", "Named after the NSW state flower"),
  'reds':        ("Reds", "Brisbane", "", ""),
  'force':       ("Western Force", "Perth", "", ""),
  'drua':        ("Fijian Drua", "Super Rugby Pacific", "2022", ""),
  'moana':       ("Moana Pasifika", "Super Rugby Pacific", "2022", ""),
  'bulls':       ("Bulls", "Pretoria", "", "Now in the United Rugby Championship"),
  'sharks':      ("Sharks", "Durban", "", "Now in the United Rugby Championship"),
  'stormers':    ("Stormers", "Cape Town", "", "Now in the United Rugby Championship"),
  'lions':       ("Lions", "Johannesburg", "", "Now in the United Rugby Championship"),
  'leinster':    ("Leinster", "Dublin", "", ""),
  'munster':     ("Munster", "Limerick & Cork", "", ""),
  'ulster':      ("Ulster", "Belfast", "", ""),
  'connacht':    ("Connacht", "Galway", "", ""),
  'toulouse':    ("Toulouse", "Top 14", "", "Most European Cup titles"),
  'larochelle':  ("La Rochelle", "Top 14", "", ""),
  'racing92':    ("Racing 92", "Top 14", "", "The 92 is the Hauts-de-Seine département"),
  'stadefr':     ("Stade Français", "Top 14", "", ""),
  'toulon':      ("Toulon", "Top 14", "", ""),
  'clermont':    ("Clermont", "Top 14", "", ""),
  'saracens':    ("Saracens", "English Premiership", "", ""),
  'tigers':      ("Leicester Tigers", "English Premiership", "", ""),
  'exeter':      ("Exeter Chiefs", "English Premiership", "", ""),
  'quins':       ("Harlequins", "English Premiership", "", ""),
  'saints':      ("Northampton Saints", "English Premiership", "", ""),
  'bath':        ("Bath", "English Premiership", "", ""),
  # players
  'lomu':        ("Jonah Lomu", "All Black wing", "1994–2002", ""),
  'mccaw':       ("Richie McCaw", "All Black flanker", "2001–2015", "Captained the 2011 and 2015 World Cup wins"),
  'carter':      ("Dan Carter", "All Black fly-half", "2003–2015", ""),
  'barrett':     ("Beauden Barrett", "All Black playmaker", "2012–", ""),
  'sbw':         ("Sonny Bill Williams", "All Black centre", "2010–2019", "Also an NRL premiership winner"),
  'kirk':        ("David Kirk", "All Black halfback", "1983–1987", "Captained the 1987 World Cup win"),
  'campese':     ("David Campese", "Wallaby wing", "1982–1996", ""),
  'gregan':      ("George Gregan", "Wallaby halfback", "1994–2007", ""),
  'eales':       ("John Eales", "Wallaby lock", "1991–2001", "Captained the 1999 World Cup win"),
  'farrjones':   ("Nick Farr-Jones", "Wallaby halfback", "1984–1993", "Captained the 1991 World Cup win"),
  'hooper':      ("Michael Hooper", "Wallaby flanker", "2012–2023", ""),
  'pocock':      ("David Pocock", "Wallaby back-rower", "2008–2019", "Now a senator"),
  'folau':       ("Israel Folau", "Wallaby fullback", "2013–2019", "Also played NRL and AFL"),
  'sailor':      ("Wendell Sailor", "Wallaby wing", "2002–2006", "Came from the Broncos"),
  'tuqiri':      ("Lote Tuqiri", "Wallaby wing", "2003–2008", "Came from the Broncos"),
  'rogers':      ("Mat Rogers", "Wallaby utility back", "2002–2006", "Came from the Sharks"),
  'suaalii':     ("Joseph Suaalii", "Wallaby centre", "2024–", "Came from the Roosters"),
  'habana':      ("Bryan Habana", "Springbok wing", "2004–2016", ""),
  'etzebeth':    ("Eben Etzebeth", "Springbok lock", "2012–", ""),
  'kolbe':       ("Cheslin Kolbe", "Springbok wing", "2018–", ""),
  'kolisi':      ("Siya Kolisi", "Springbok flanker", "2013–", "Captained the 2019 and 2023 World Cup wins"),
  'pienaar':     ("Francois Pienaar", "Springbok flanker", "1993–1996", "Captained the 1995 World Cup win"),
  'smit':        ("John Smit", "Springbok hooker", "2000–2011", "Captained the 2007 World Cup win"),
  'odriscoll':   ("Brian O'Driscoll", "Ireland centre", "1999–2014", ""),
  'sexton':      ("Johnny Sexton", "Ireland fly-half", "2009–2023", ""),
  'oconnell':    ("Paul O'Connell", "Ireland lock", "2002–2015", ""),
  'ogara':       ("Ronan O'Gara", "Ireland fly-half", "2000–2013", ""),
  'gedwards':    ("Gareth Edwards", "Wales scrum-half", "1967–1978", ""),
  'swilliams':   ("Shane Williams", "Wales wing", "2000–2011", ""),
  'awj':         ("Alun Wyn Jones", "Wales lock", "2006–2023", "Most-capped Test player ever"),
  'halfpenny':   ("Leigh Halfpenny", "Wales fullback", "2008–2023", ""),
  'hogg':        ("Stuart Hogg", "Scotland fullback", "2012–2023", ""),
  'russell':     ("Finn Russell", "Scotland fly-half", "2014–", ""),
  'hastings':    ("Gavin Hastings", "Scotland fullback", "1986–1995", ""),
  'weir':        ("Doddie Weir", "Scotland lock", "1990–2000", ""),
  'dupont':      ("Antoine Dupont", "France scrum-half", "2017–", ""),
  'blanco':      ("Serge Blanco", "France fullback", "1980–1991", ""),
  'dusautoir':   ("Thierry Dusautoir", "France flanker", "2006–2015", ""),
  'galthie':     ("Fabien Galthié", "France scrum-half, now coach", "1991–2003", ""),
  'wilkinson':   ("Jonny Wilkinson", "England fly-half", "1998–2011", "Drop goal to win the 2003 final"),
  'mjohnson':    ("Martin Johnson", "England lock", "1993–2003", "Captained the 2003 World Cup win"),
  'farrell':     ("Owen Farrell", "England fly-half/centre", "2012–2023", ""),
  'itoje':       ("Maro Itoje", "England lock", "2016–", ""),
  'robinson':    ("Jason Robinson", "England wing/fullback", "2001–2007", "Came from rugby league (Wigan)"),
  # coaches
  'lochore':     ("Brian Lochore", "Coach", "", "Won the 1987 World Cup with New Zealand"),
  'dwyer':       ("Bob Dwyer", "Coach", "", "Won the 1991 World Cup with Australia"),
  'christie':    ("Kitch Christie", "Coach", "", "Won the 1995 World Cup with South Africa"),
  'macqueen':    ("Rod Macqueen", "Coach", "", "Won the 1999 World Cup with Australia"),
  'woodward':    ("Clive Woodward", "Coach", "", "Won the 2003 World Cup with England"),
  'jwhite':      ("Jake White", "Coach", "", "Won the 2007 World Cup with South Africa"),
  'henry':       ("Graham Henry", "Coach", "", "Won the 2011 World Cup with New Zealand; earlier coached Wales"),
  'hansen':      ("Steve Hansen", "Coach", "", "Won the 2015 World Cup with New Zealand; earlier coached Wales"),
  'erasmus':     ("Rassie Erasmus", "Coach", "", "Won the 2019 World Cup with South Africa"),
  'nienaber':    ("Jacques Nienaber", "Coach", "", "Won the 2023 World Cup with South Africa"),
  'ejones':      ("Eddie Jones", "Coach", "", "Coached Australia, Japan, England"),
  'cheika':      ("Michael Cheika", "Coach", "", "Coached Australia, then Argentina"),
  'rennie':      ("Dave Rennie", "Coach (New Zealander)", "", "Coached Australia 2020–23"),
  'schmidt':     ("Joe Schmidt", "Coach (New Zealander)", "", "Coached Ireland, then Australia"),
  'deans':       ("Robbie Deans", "Coach (New Zealander)", "", "Coached Australia 2008–13"),
  'mckenzie':    ("Ewen McKenzie", "Coach", "", "Coached Australia 2013–14"),
  'gatland':     ("Warren Gatland", "Coach (New Zealander)", "", "Coached Wales and the Lions"),
  'jjoseph':     ("Jamie Joseph", "Coach (New Zealander)", "", "Coached Japan 2016–23"),
  # grounds
  'edenpark':    ("Eden Park", "Auckland", "", "Hosted the 1987 and 2011 finals"),
  'twickenham':  ("Twickenham", "London", "", "Hosted the 1991 and 2015 finals"),
  'principality':("Principality Stadium", "Cardiff", "", "As the Millennium Stadium, hosted the 1999 final"),
  'ellispark':   ("Ellis Park", "Johannesburg", "", "Hosted the 1995 final"),
  'stadiumaus':  ("Stadium Australia", "Sydney", "", "Hosted the 2003 final"),
  'sdf':         ("Stade de France", "Paris", "", "Hosted the 2007 and 2023 finals"),
  'yokohama':    ("Yokohama Stadium", "Japan", "", "Hosted the 2019 final"),
  'murrayfield': ("Murrayfield", "Edinburgh", "", ""),
  'aviva':       ("Aviva Stadium", "Dublin", "", "Formerly Lansdowne Road"),
  'olimpico':    ("Stadio Olimpico", "Rome", "", ""),
  # trophies, dances, game
  'bledisloe':   ("Bledisloe Cup", "New Zealand v Australia", "1932", "Named after Lord Bledisloe"),
  'calcutta':    ("Calcutta Cup", "England v Scotland", "1879", "Made from melted-down rupees"),
  'freedom':     ("Freedom Cup", "New Zealand v South Africa", "2004", ""),
  'mandela':     ("Mandela Challenge Plate", "Australia v South Africa", "2000", "Named after Nelson Mandela"),
  'quaich':      ("Centenary Quaich", "Ireland v Scotland", "1989", ""),
  'garibaldi':   ("Garibaldi Trophy", "France v Italy", "2007", "Named after Giuseppe Garibaldi"),
  'webbellis':   ("Webb Ellis Cup", "The World Cup trophy", "1987", "Named after William Webb Ellis"),
  'haka':        ("Haka", "New Zealand", "", ""),
  'sivatau':     ("Siva Tau", "Samoa", "", ""),
  'sipitau':     ("Sipi Tau", "Tonga", "", ""),
  'cibi':        ("Cibi", "Fiji", "", ""),
  'hooker':      ("Hooker", "Position", "", "Wears 2"),
  'prop':        ("Prop", "Position", "", "Wears 1 or 3"),
  'lock':        ("Lock", "Position", "", "Wears 4 or 5"),
  'flanker':     ("Flanker", "Position", "", "Wears 6 or 7"),
  'number8':     ("Number 8", "Position", "", ""),
  'scrumhalf':   ("Scrum-half", "Position", "", "Wears 9"),
  'flyhalf':     ("Fly-half", "Position", "", "Wears 10"),
  'centre':      ("Centre", "Position", "", "Wears 12 or 13"),
  'wing':        ("Wing", "Position", "", "Wears 11 or 14"),
  'fullback':    ("Fullback", "Position", "", "Wears 15"),
  'scrum':       ("Scrum", "Set piece", "", ""),
  'lineout':     ("Lineout", "Set piece", "", ""),
  'ruck':        ("Ruck", "Breakdown", "", ""),
  'maul':        ("Maul", "Breakdown", "", ""),
  'try':         ("Try", "Scoring", "", "5 points"),
  'conversion':  ("Conversion", "Scoring", "", "2 points"),
  'dropgoal':    ("Drop goal", "Scoring", "", "3 points"),
  'penaltytry':  ("Penalty try", "Scoring", "", "7 points"),
  # emblems
  'silverfern':  ("Silver Fern", "Emblem", "", "New Zealand"),
  'rose':        ("Rose", "Emblem", "", "England"),
  'thistle':     ("Thistle", "Emblem", "", "Scotland"),
  'shamrock':    ("Shamrock", "Emblem", "", "Ireland"),
  'protea':      ("Protea", "Emblem", "", "South Africa"),
  'cockerel':    ("Cockerel", "Emblem", "", "France"),
  # --- added for variety ---
  'mcgeechan':   ("Ian McGeechan", "Coach", "", "Coached the Lions on four tours"),
  'afarrell':    ("Andy Farrell", "Coach", "", "Coached Ireland and the 2025 Lions"),
  'knockon':     ("Knock-on", "Infringement", "", ""),
  'forwardpass': ("Forward pass", "Infringement", "", ""),
  'offside':     ("Offside", "Infringement", "", ""),
  'hightackle':  ("High tackle", "Infringement", "", ""),
  'sinbin':      ("Sin bin", "Referee's toolkit", "", "Ten minutes off"),
  'tmo':         ("TMO", "Referee's toolkit", "", "Television match official"),
  'yellowcard':  ("Yellow card", "Referee's toolkit", "", ""),
  'advantage':   ("Advantage", "Referee's toolkit", "", ""),
  'wallaroos':   ("Wallaroos", "Australia women", "", ""),
  'lesbleues':   ("Les Bleues", "France women", "", ""),
}

CATEGORIES = [
  C('sixnations', 0, "Six Nations teams", ['england','france','ireland','scotland','wales','italy']),
  C('rugbychamp', 0, "Rugby Championship teams", ['allblacks','springboks','wallabies','pumas']),
  C('dances', 0, "Pre-match war dances", ['haka','sivatau','sipitau','cibi']),
  C('nzsuper', 0, "New Zealand Super Rugby sides", ['crusaders','blues','chiefs','hurricanes','highlanders']),
  C('irish', 0, "Irish provinces", ['leinster','munster','ulster','connacht']),
  C('forwards', 0, "Forward positions", ['hooker','prop','lock','flanker','number8']),
  C('backs', 0, "Positions in the backs", ['scrumhalf','flyhalf','centre','wing','fullback']),
  C('setpiece', 0, "Scrums & breakdowns", ['scrum','lineout','ruck','maul']),
  C('scoring', 0, "Ways to score", ['try','conversion','dropgoal','penaltytry']),
  C('pacific', 0, "From the Pacific Islands", ['fiji','samoa','tonga','drua','moana']),

  C('wcwin', 1, "World Cup winners", ['allblacks','springboks','wallabies','england'], also=['blackferns','redroses','wallaroos','lesbleues']),
  C('aussuper', 1, "Australian Super Rugby sides", ['brumbies','waratahs','reds','force']),
  C('urc', 1, "South African sides", ['bulls','sharks','stormers','lions']),
  C('top14', 1, "French clubs", ['toulouse','larochelle','racing92','stadefr','toulon','clermont']),
  C('prem', 1, "English clubs", ['saracens','tigers','exeter','quins','saints','bath']),
  C('abplayers', 1, "All Blacks", ['lomu','mccaw','carter','barrett','sbw','kirk']),
  C('wbplayers', 1, "Wallabies", ['campese','gregan','eales','farrjones','hooper','pocock'],
    also=['folau','sailor','tuqiri','rogers','suaalii']),
  C('boks', 1, "Springboks", ['habana','etzebeth','kolbe','kolisi','pienaar','smit']),
  C('irl', 1, "Ireland greats", ['odriscoll','sexton','oconnell','ogara']),
  C('wal', 1, "Wales greats", ['gedwards','swilliams','awj','halfpenny']),
  C('sco', 1, "Scotland greats", ['hogg','russell','hastings','weir']),
  C('fra', 1, "France greats", ['dupont','blanco','dusautoir','galthie']),
  C('eng', 1, "England greats", ['wilkinson','mjohnson','farrell','itoje','robinson']),
  C('sixgrounds', 1, "Six Nations home grounds", ['twickenham','murrayfield','principality','aviva','sdf','olimpico']),
  C('twoteam', 1, "Trophies contested by just two nations", ['bledisloe','calcutta','freedom','mandela','quaich','garibaldi']),
  C('europe', 1, "Emerging European nations", ['georgia','portugal','romania','spain'], also=['italy']),

  C('wccapt', 2, "Captained a World Cup win", ['kirk','farrjones','pienaar','eales','mjohnson','smit','mccaw','kolisi']),
  C('wccoach', 2, "Coached a World Cup win", ['lochore','dwyer','christie','macqueen','woodward','jwhite','henry','hansen',
                                               'erasmus','nienaber']),
  C('wbcoach', 2, "Coached the Wallabies", ['ejones','cheika','rennie','schmidt','deans','mckenzie'],
    also=['macqueen','dwyer']),
  C('kiwiabroad', 2, "New Zealanders who coached other nations", ['rennie','schmidt','deans','gatland','jjoseph'],
    also=['henry','hansen'], memory=True),
  C('finals', 2, "Hosted a World Cup final", ['edenpark','twickenham','principality','ellispark','stadiumaus','sdf','yokohama'],
    memory=True),
  C('codes', 2, "Also played rugby league", ['sbw','folau','sailor','tuqiri','rogers','suaalii','robinson']),
  C('emblems', 2, "Emblems on the jersey", ['silverfern','rose','thistle','shamrock','protea','cockerel'],
    also=['springboks','braveblossoms']),

  C('animals', 3, "Named after animals", ['springboks','wallabies','pumas','bulls','sharks','brumbies','lions','tigers','wallaroos'],
    also=['cockerel']),
  C('colours', 3, "A colour in the name", ['blues','reds','allblacks','blackferns','redroses','lesbleues'],
    key={'blues':'Blues','reds':'Reds','allblacks':'Blacks','blackferns':'Black','redroses':'Red','lesbleues':'Bleues'}),
  C('plants', 3, "Plants & flowers", ['silverfern','rose','thistle','shamrock','protea','waratahs','braveblossoms'],
    also=['blackferns','redroses']),
  C('history', 3, "Historical figures", ['crusaders','saracens','barbarians','quins','highlanders']),
  C('person', 3, "Named after a person", ['webbellis','bledisloe','mandela','garibaldi'], also=['ellispark','edenpark']),
  # --- added for variety ---
  C('locks', 1, "Locks", ['eales','oconnell','awj','etzebeth','itoje','mjohnson','weir'], also=['lock']),
  C('tens', 1, "Fly-halves", ['carter','wilkinson','sexton','ogara','russell'], also=['barrett','farrell','flyhalf']),
  C('nines', 1, "Scrum-halves", ['dupont','gregan','gedwards','galthie','kirk','farrjones'], also=['scrumhalf']),
  C('wingers', 1, "Wingers", ['lomu','campese','habana','swilliams'], also=['kolbe','sailor','tuqiri','robinson','wing']),
  C('fullbacks', 1, "Fullbacks", ['hogg','halfpenny','blanco','hastings'], also=['folau','robinson','fullback','barrett']),
  C('flankers', 1, "Flankers", ['mccaw','hooper','pocock','kolisi','pienaar','dusautoir'], also=['flanker']),
  C('lions', 2, "Coached the British & Irish Lions", ['gatland','woodward','mcgeechan','afarrell'], also=['henry']),
  C('infringe', 0, "Infringements", ['knockon','forwardpass','offside','hightackle']),
  C('ref', 0, "The referee's toolkit", ['sinbin','tmo','yellowcard','advantage']),
  C('women', 1, "Women's national teams", ['blackferns','redroses','wallaroos','lesbleues']),
  C('everyday', 3, "Positions that are everyday words", ['hooker','prop','lock','wing','centre']),
]

if __name__ == '__main__':
    run(ITEMS, CATEGORIES, 'rugby', 'RUGBY', seed=1, n=50, caps=(4, 6), window=7)
