#!/usr/bin/env python3
"""Builds nrl.js: the modern NRL edition.  Run: python3 connections/tools/build_nrl.py [-v]"""
from edition import C, run

# id: (tile, clue, era, note for the results screen)
ITEMS = {
  # clubs
  'broncos':     ("Broncos", "Brisbane", "1988", "Coached by Wayne Bennett 1988–2008, 2015–18"),
  'cowboys':     ("Cowboys", "Townsville", "1995", "First premiership in 2015"),
  'titans':      ("Titans", "Gold Coast", "2007", "Yet to win a premiership"),
  'dolphins':    ("Dolphins", "Redcliffe", "2023", "Wayne Bennett was their first coach"),
  'storm':       ("Storm", "Melbourne", "1998", ""),
  'raiders':     ("Raiders", "Canberra", "1982", ""),
  'warriors':    ("Warriors", "Auckland", "1995", "Yet to win a premiership"),
  'bears':       ("Perth Bears", "Joins in 2027", "2027", ""),
  'bulldogs':    ("Bulldogs", "Canterbury-Bankstown", "1935", ""),
  'sharks':      ("Sharks", "Cronulla", "1967", "First premiership in 2016"),
  'seaeagles':   ("Sea Eagles", "Manly", "1947", ""),
  'eels':        ("Eels", "Parramatta", "1947", ""),
  'panthers':    ("Panthers", "Penrith", "1967", "Four straight premierships, 2021–24"),
  'rabbitohs':   ("Rabbitohs", "South Sydney", "1908", ""),
  'roosters':    ("Roosters", "Eastern Suburbs", "1908", ""),
  'wtigers':     ("Wests Tigers", "Balmain & Wests", "2000", ""),
  'dragons':     ("Dragons", "St George Illawarra", "1999", ""),
  'knights':     ("Knights", "Newcastle", "1988", ""),
  # fan nicknames
  'bunnies':     ("Bunnies", "Fan nickname", "", "South Sydney Rabbitohs"),
  'chooks':      ("Chooks", "Fan nickname", "", "Sydney Roosters"),
  'silvertails': ("Silvertails", "Fan nickname", "", "Manly Sea Eagles"),
  'redv':        ("Red V", "Fan nickname", "", "St George Illawarra Dragons"),
  # players
  'csmith':      ("Cameron Smith", "Storm hooker", "2002–2020", ""),
  'cronk':       ("Cooper Cronk", "Halfback", "2004–2019", "Storm, then Roosters"),
  'slater':      ("Billy Slater", "Storm fullback", "2003–2018", "Now Queensland's Origin coach"),
  'thurston':    ("Johnathan Thurston", "Cowboys halfback", "2002–2018", "Captained the 2015 premiership"),
  'lockyer':     ("Darren Lockyer", "Broncos fullback/five-eighth", "1995–2011", ""),
  'inglis':      ("Greg Inglis", "Centre/fullback", "2005–2019", "Storm, then Rabbitohs"),
  'ncleary':     ("Nathan Cleary", "Panthers halfback", "2016–", "Coached by his dad, Ivan"),
  'luai':        ("Jarome Luai", "Five-eighth", "2018–", "Panthers, then Wests Tigers"),
  'yeo':         ("Isaah Yeo", "Panthers lock", "2014–", ""),
  'edwards':     ("Dylan Edwards", "Panthers fullback", "2014–", ""),
  'too':         ("Brian To'o", "Panthers winger", "2019–", ""),
  'tedesco':     ("James Tedesco", "Roosters fullback", "2012–", ""),
  'ponga':       ("Kalyn Ponga", "Knights fullback", "2016–", ""),
  'walsh':       ("Reece Walsh", "Broncos fullback", "2021–", ""),
  'dce':         ("Daly Cherry-Evans", "Halfback", "2011–", "Long-time Manly captain"),
  'moses':       ("Mitchell Moses", "Eels halfback", "2014–", ""),
  'hynes':       ("Nicho Hynes", "Sharks halfback", "2019–", ""),
  'grant':       ("Harry Grant", "Storm hooker", "2018–", ""),
  'koroisau':    ("Api Koroisau", "Hooker", "2012–", "Panthers 2021 premiership, then Wests Tigers"),
  'cook':        ("Damien Cook", "Hooker", "2013–", "Long-time Rabbitoh"),
  'munster':     ("Cameron Munster", "Storm five-eighth", "2014–", ""),
  'hayne':       ("Jarryd Hayne", "Fullback/winger", "2006–2018", "Also tried the NFL and Fiji sevens"),
  'sbw':         ("Sonny Bill Williams", "Back-rower", "2004–2020", "Also an All Black"),
  'folau':       ("Israel Folau", "Winger/centre", "2007–2010", "Also a Wallaby and an AFL player"),
  'sailor':      ("Wendell Sailor", "Winger", "1993–2009", "Also a Wallaby"),
  'tuqiri':      ("Lote Tuqiri", "Winger", "1999–2011", "Also a Wallaby"),
  'rogers':      ("Mat Rogers", "Utility back", "1995–2011", "Also a Wallaby"),
  'suaalii':     ("Joseph Suaalii", "Roosters centre", "2021–2024", "Switched to the Wallabies"),
  # nicknames
  'turbo':       ("Turbo", "Player nickname", "", "Tom Trbojevic"),
  'foxx':        ("The Foxx", "Player nickname", "", "Josh Addo-Carr"),
  'joey':        ("Joey", "Player nickname", "", "Andrew Johns"),
  'freddy':      ("Freddy", "Player nickname", "", "Brad Fittler"),
  # coaches
  'bennett':     ("Wayne Bennett", "Coach", "", "Won the 2010 premiership with the Dragons"),
  'toovey':      ("Geoff Toovey", "Coach", "", "Won the 2011 premiership with Manly"),
  'bellamy':     ("Craig Bellamy", "Storm coach", "2003–", ""),
  'trobinson':   ("Trent Robinson", "Roosters coach", "2013–", "Won the 2013, 2018 and 2019 premierships"),
  'maguire':     ("Michael Maguire", "Coach", "", "Won the 2014 premiership with Souths"),
  'green':       ("Paul Green", "Coach", "", "Won the 2015 premiership with the Cowboys"),
  'flanagan':    ("Shane Flanagan", "Coach", "", "Won the 2016 premiership with the Sharks"),
  'icleary':     ("Ivan Cleary", "Panthers coach", "2019–", "Won four straight premierships, 2021–24"),
  'ajohnston':   ("Alex Johnston", "Rabbitohs winger", "2014–", "Premiership-era try-scoring record holder"),
  'coates':      ("Xavier Coates", "Storm winger", "2019–", ""),
  'holmes':      ("Valentine Holmes", "Winger/fullback", "2014–", "Also tried the NFL"),
  'meninga':     ("Mal Meninga", "Coach", "", "Coached Queensland's eight-in-a-row, then the Kangaroos"),
  'kwalters':    ("Kevin Walters", "Coach", "", "Coached Queensland 2020–22, then the Broncos"),
  'daley':       ("Laurie Daley", "Coach", "", "Coached NSW 2013–17"),
  'magic':       ("Magic Round", "Fixture", "2019", "A whole round at Suncorp Stadium"),
  'vegas':       ("Las Vegas", "Fixture", "2024", "Season openers at Allegiant Stadium"),
  'origin':      ("State of Origin", "Fixture", "", "NSW v Queensland"),
  'allstars':    ("All Stars", "Fixture", "", "Indigenous v Māori"),
  # awards & rules
  'dallym':      ("Dally M Medal", "Award", "", "Player of the year"),
  'churchill':   ("Clive Churchill Medal", "Award", "", "Best on ground in the grand final"),
  'provan':      ("Provan-Summons Trophy", "Award", "", "The premiership trophy"),
  'wallylewis':  ("Wally Lewis Medal", "Award", "", "Player of the State of Origin series"),
  'sixagain':    ("Six again", "Rule", "2020", ""),
  'challenge':   ("Captain's challenge", "Rule", "2020", ""),
  'kick2040':    ("20/40 kick", "Rule", "2021", ""),
  'bunker':      ("The Bunker", "Video review", "2016", ""),
  'goldenpoint': ("Golden point", "Extra time", "2003", ""),
}

CATEGORIES = [
  C('qld', 0, "Queensland clubs", ['broncos','cowboys','titans','dolphins']),
  C('outside', 0, "Not from NSW or Queensland", ['storm','raiders','warriors','bears']),
  C('sydney', 0, "Sydney clubs", ['bulldogs','sharks','seaeagles','eels','panthers','rabbitohs','roosters','wtigers'],
    also=['dragons']),
  C('sea', 0, "Something from the sea", ['sharks','dolphins','eels','seaeagles']),
  C('awards', 0, "Medals & trophies", ['dallym','churchill','provan','wallylewis']),
  C('fullbacks', 0, "Fullbacks", ['slater','tedesco','ponga','walsh','edwards'], also=['turbo','inglis','hayne','lockyer']),

  C('stormera', 1, "The Storm's Big Three — and their coach", ['csmith','cronk','slater','bellamy'], also=['munster','grant','inglis']),
  C('fourpeat', 1, "Penrith's 2021–24 four-peat", ['ncleary','luai','yeo','edwards','too'], also=['icleary','koroisau']),
  C('halves', 1, "Halfbacks", ['cronk','thurston','ncleary','dce','moses','hynes'], also=['luai','munster','lockyer','joey','freddy']),
  C('hookers', 1, "Hookers", ['csmith','grant','koroisau','cook']),
  C('rules', 1, "Brought in since 2016", ['sixagain','challenge','kick2040','bunker'], also=['goldenpoint']),
  C('fighters', 1, "Fighters & warriors", ['knights','raiders','warriors','titans'], also=['dragons','cowboys']),
  C('neverwon', 1, "Yet to win a premiership", ['titans','warriors','dolphins','bears']),
  C('codes', 1, "Also played rugby union", ['sbw','folau','sailor','tuqiri','rogers','suaalii'], also=['hayne']),

  C('wingers', 1, "Wingers", ['too','ajohnston','coates','sailor','tuqiri'], also=['foxx','hayne','folau','holmes','rogers','inglis']),
  C('fixtures', 1, "On the calendar", ['magic','vegas','origin','allstars']),
  C('newclubs', 2, "Joined the competition since 1995", ['cowboys','warriors','storm','titans','dolphins','bears'],
    also=['wtigers','dragons']),
  C('origincoach', 2, "Coached in State of Origin", ['meninga','kwalters','daley','maguire'], also=['slater','freddy']),
  C('coaches', 2, "Coached a premiership since 2010", ['bennett','toovey','bellamy','trobinson','maguire','green','flanagan','icleary']),
  C('bennettclubs', 2, "Coached by Wayne Bennett", ['broncos','dragons','knights','rabbitohs','dolphins'], memory=True),
  C('premiers10s', 2, "Premiers in the 2010s", ['dragons','seaeagles','storm','roosters','rabbitohs','cowboys','sharks'], memory=True),

  C('fannames', 3, "Fan nicknames", ['bunnies','chooks','silvertails','redv'],
    gloss={'bunnies':'Rabbitohs','chooks':'Roosters','silvertails':'Sea Eagles','redv':'Dragons'}),
  C('playernames', 3, "Player nicknames", ['turbo','foxx','joey','freddy'],
    gloss={'turbo':'Tom Trbojevic','foxx':'Josh Addo-Carr','joey':'Andrew Johns','freddy':'Brad Fittler'}),
]

if __name__ == '__main__':
    run(ITEMS, CATEGORIES, 'nrl', 'NRL', seed=20080101, n=50, caps=(7, 14))
