"""Shared runner for the newer editions: validates the tables, builds the bank with the
build_puzzles.py engine and writes <out>.js."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_puzzles as engine

def C(id, level, name, members, also=(), key=None, gloss=None, memory=False):
    return dict(id=id, level=level, name=name, members=list(members), also=list(also),
                key=key or {}, gloss=gloss or {}, memory=memory)

def run(items, categories, out, var, seed, n, caps=(3, 6), window=8, repeat_gap=10**6, seeds=5):
    for c in categories:
        for b in c['members'] + c['also'] + list(c['key']) + list(c['gloss']):
            assert b in items, (c['id'], b)
        assert not set(c['members']) & set(c['also']), c['id']
        assert len(c['members']) >= 4, c['id']
        for b, k in c['key'].items():
            assert k.lower() in items[b][0].lower(), (c['id'], b, k)
    engine.CATEGORIES = categories
    engine.DECOY_OK = set()
    engine.CAP_SMALL, engine.CAP_BIG = caps
    engine.WINDOW, engine.REPEAT_GAP, engine.POOL_TRIES = window, repeat_gap, 2
    for s in range(seed, seed + seeds):
        try:
            puzzles, cat_use, tile_use = engine.build(n=n, seed=s)
            break
        except RuntimeError:
            continue
    else:
        raise SystemExit('no seed produced a full bank')
    data = {
        'books': {k: {'t': t, 'a': a, 'm': m, 'n': nn} for k, (t, a, m, nn) in items.items()},
        'categories': {c['id']: {'name': c['name'], 'level': c['level'], 'key': c['key'], 'gloss': c['gloss']} for c in categories},
        'puzzles': [[{'c': cid, 'b': bs} for cid, bs in p['groups']] for p in puzzles],
    }
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', out + '.js')
    with open(path, 'w') as f:
        f.write(f'// Generated by tools/build_{out}.py — edit that file, not this one.\n')
        f.write(f'window.{var} = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print(f'seed {s}: {len(puzzles)} puzzles from {len(items)} items')
    print('category use:', dict(sorted(cat_use.items(), key=lambda x: -x[1])))
    print('unused:', [b for b in items if not tile_use[b]])
    if '-v' in sys.argv:
        cat = {c['id']: c for c in categories}
        for i, p in enumerate(puzzles, 1):
            print(f'#{i}')
            for cid, bs in p['groups']:
                print(f"  {cat[cid]['level']} {cat[cid]['name']:<40} " + ' | '.join(items[b][0] for b in bs))
